/*
|--------------------------------------------------------------------------
| Sitemap + robots generator
|--------------------------------------------------------------------------
| Fetches the live backend API and writes public/sitemap.xml (including every
| package and blog detail page) plus public/robots.txt pointing at it.
| Runs automatically before every build via the "prebuild" script.
|
| Env:
|   API_URL   – backend base, e.g. https://api.roambeyond.travel/api  (default http://localhost:5000/api)
|   SITE_URL  – public origin, e.g. https://roambeyond.travel            (default http://localhost:3000)
|--------------------------------------------------------------------------
*/
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const API_BASE = (process.env.API_URL || 'http://localhost:5000/api').replace(/\/$/, '');
const SITE_URL = (process.env.SITE_URL || 'http://localhost:3000').replace(/\/$/, '');

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../public');
const today = new Date().toISOString().slice(0, 10);

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

async function collect(path, listKey, limit) {
  const items = [];
  for (let page = 1; page <= 30; page += 1) {
    const res = await fetch(`${API_BASE}${path}?page=${page}&limit=${limit}`);
    if (!res.ok) throw new Error(`GET ${path} failed: ${res.status}`);
    const json = await res.json();
    const rows = json?.data?.[listKey] || json?.data?.data || json?.data || [];
    items.push(...rows);
    const total = json?.data?.pagination?.total;
    if (!total || items.length >= total || rows.length < limit) break;
  }
  return items;
}

const staticUrls = [
  ['/', 'daily', '1.0'],
  ['/packages', 'weekly', '0.9'],
  ['/destinations', 'weekly', '0.8'],
  ['/blogs', 'weekly', '0.8'],
  ['/contact', 'monthly', '0.6'],
  ['/search', 'monthly', '0.4'],
];

const warnings = [];

try {
  const packages = await collect('/packages', 'data', 50);
  for (const p of packages) {
    if (p?.slug) staticUrls.push([`/packages/${encodeURIComponent(p.slug)}`, 'weekly', '0.9']);
  }
} catch (e) {
  warnings.push(`packages: ${e.message}`);
}

try {
  const blogs = await collect('/blogs', 'blogs', 50);
  for (const b of blogs) {
    if (b?.slug) staticUrls.push([`/blogs/${encodeURIComponent(b.slug)}`, 'monthly', '0.6']);
  }
} catch (e) {
  warnings.push(`blogs: ${e.message}`);
}

const urlTags = staticUrls
  .map(
    ([loc, freq, prio]) =>
      `  <url>\n    <loc>${SITE_URL}${esc(loc)}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${freq}</changefreq>\n    <priority>${prio}</priority>\n  </url>`
  )
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlTags}
</urlset>
`;

const robots = `# Roam Beyond — crawl rules (generated by scripts/generate-sitemap.mjs)
User-agent: *
Allow: /

# Private / authenticated areas
Disallow: /admin
Disallow: /dashboard
Disallow: /login
Disallow: /register
Disallow: /forgot-password
Disallow: /reset-password
Disallow: /wishlist
Disallow: /notifications

# API and docs
Disallow: /api
Disallow: /api-docs

Sitemap: ${SITE_URL}/sitemap.xml
`;

mkdirSync(OUT, { recursive: true });
writeFileSync(resolve(OUT, 'sitemap.xml'), xml, 'utf8');
writeFileSync(resolve(OUT, 'robots.txt'), robots, 'utf8');

console.log(`sitemap.xml written with ${staticUrls.length} URLs (SITE_URL=${SITE_URL})`);
if (warnings.length) {
  console.warn(`WARN: sitemap is partial — ${warnings.join('; ')}`);
}
